
OBJ_DIR:=.obj-gcc
COMP:=gcc
EXE:=test-gcc

#CPP_OPTS=-std=c++17  -pedantic -Wall -Wextra -Wshadow -Werror  
CPP_OPTS=-std=c++17  -pedantic -Wall -Wshadow -Werror  
LD_OPTS=-lstdc++ -lgtest -lpthread 

-include Makefile.common

